### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by typo3ua** [mslinn/jekyll_flexible_include_plugin#2]
I did...
```
Copy flexible_include.rb into /_plugins
```
then...
```
{% flexible_include '/assets/js/my.js' %}
```
or...
```
{% flexible_include 'assets/js/my.js' %}
```
I get error
```
flexible_include.rb: No such file or directory @ rb_sysopen - /assets/js/my.js
  Liquid Exception: flexible_include.rb: No such file or directory @ rb_sysopen - /assets/js/my.js in /github/workspace/_layouts/my.html
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/github/workspace/_plugins/flexible_include.rb:140:in `abort': flexible_include.rb: No such file or directory @ rb_sysopen - /assets/js/my.js (SystemExit)
	from /github/workspace/_plugins/flexible_include.rb:140:in `rescue in render'
	from /github/workspace/_plugins/flexible_include.rb:135:in `render'
```
or...
```
   Liquid Exception: no implicit conversion of nil into String in /github/workspace/_layouts/my.html
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/github/workspace/_plugins/flexible_include.rb:130:in `join': no implicit conversion of nil into String (TypeError)
	from /github/workspace/_plugins/flexible_include.rb:130:in `render'
```
What is wrong did I do?

**Comment by mslinn** [comment]
Possible reasons for this error message are:

 -  A directory called `assets/js`, based at the top of your Jekyll project, does not exist
 - The directory exists but does not contain a file called `my.js`
 - The directory and/or file lacks read permission.
